### ISSUE TITLE
Review in progress

### ISSUE THREAD

**Issue by zahraoui-mohammed** [Charaf99X/CodingChallenge#1]
Hello Mr @Charaf99X ,

After reviewing your latest updates, here are some points that require your attention. It is essential to carefully address these items, as they directly impact the overall quality and functionality of the application:
  
- Return types and type hints are missing.
- Follow PSR 1-2 notations.
- The service layer is important to ensure DRY principle.
- Implement dynamic routes based on the backend.

Please ensure that all the above issues are rectified. It is important to carefully follow the instructions and review the "Links and Resources" section to avoid missing any key components. Your attention to these details is critical to ensure the strength of your coding quality.

**Comment by Charaf99X** [comment]
Hello Mr. @zahraoui-mohammed ,

Thank you for your feedback and for bringing these points to my attention. I have reviewed your comments and made the necessary changes to address the issues you highlighted:

Added the return types and type hints.
Followed PSR 1-2 notations as required.
Refactored the code to better adhere to the DRY principle by improving the service layer.
Implemented dynamic routes based on the backend as per your suggestion.
Please feel free to review the latest updates, and let me know if there are any further adjustments needed.
